# Generated by Django 5.2.15 on 2026-07-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructorpayout',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='instructorpayout',
            name='admin_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instructorpayout',
            name='payout_account',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='instructorpayout',
            name='payout_method',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='instructorpayout',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructorpayout',
            name='requested_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instructorpayout',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='requested', max_length=20),
        ),
    ]
