# Generated by Django 5.2.15 on 2026-07-04 03:35

import acadeval.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assignment-submissions/', validators=[acadeval.validators.validate_document_upload]),
        ),
    ]
