# Generated by Django 5.2.15 on 2026-07-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faq_blogpost_supportticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('paragraph', 'Paragraph'), ('subtitle', 'Subtitle'), ('section', 'Section'), ('code', 'Code Fence'), ('output', 'Output'), ('screenshot', 'Screenshot'), ('table', 'Table'), ('tile', 'Tile'), ('quote', 'Quote'), ('callout', 'Callout')], default='paragraph', max_length=30)),
                ('order', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('subtitle', models.CharField(blank=True, max_length=220)),
                ('body', models.TextField(blank=True)),
                ('code_language', models.CharField(blank=True, max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog-blocks/')),
                ('image_alt', models.CharField(blank=True, max_length=180)),
                ('table_data', models.TextField(blank=True, help_text='Use one row per line and separate columns with |. The first row is rendered as the table header.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.blogpost')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
