# Generated by Django 5.2.15 on 2026-07-04 03:35

import acadeval.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcontentblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog-blocks/', validators=[acadeval.validators.validate_image_upload]),
        ),
    ]
