# Generated by Django 5.2.15 on 2026-07-04 03:35

import acadeval.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', validators=[acadeval.validators.validate_pdf_upload]),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='certificate-qr/', validators=[acadeval.validators.validate_image_upload]),
        ),
    ]
