# Generated by Django 5.2.15 on 2026-07-01 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_role_666d59_idx',
            old_name='accounts_cu_role_fa5c4d_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_email_5ce40b_idx',
            old_name='accounts_cu_email_4d43e6_idx',
        ),
    ]
