# Generated by Django 5.2.15 on 2026-07-03 04:56

import accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_accounts_cu_role_fa5c4d_idx_accounts_cu_role_666d59_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
    ]
