# Generated by Django 5.2.15 on 2026-07-04 03:35

import acadeval.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/', validators=[acadeval.validators.validate_image_upload]),
        ),
    ]
