# Generated by Django 5.2.15 on 2026-07-04 03:35

import acadeval.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lessoncontentblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='course-thumbnails/', validators=[acadeval.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lesson-files/', validators=[acadeval.validators.validate_document_upload]),
        ),
        migrations.AlterField(
            model_name='lessoncontentblock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lesson-blocks/', validators=[acadeval.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='lessonresource',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lesson-resources/', validators=[acadeval.validators.validate_document_upload]),
        ),
    ]
